/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lichao_javafilepach_FileUtils */

#ifndef _Included_com_lichao_javafilepach_FileUtils
#define _Included_com_lichao_javafilepach_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lichao_javafilepach_FileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_lichao_javafilepach_FileUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_lichao_javafilepach_FileUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_lichao_javafilepach_FileUtils_patch
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
